# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
