# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_delete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hindi',
            field=models.CharField(default='hindi', max_length=500),
        ),
        migrations.AddField(
            model_name='word',
            name='punjabi',
            field=models.CharField(default='punjabi', max_length=500),
        ),
    ]
