# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20171015_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
                ('tags', models.CharField(default='quote', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='word',
            name='tags',
            field=models.CharField(default='word', max_length=1000),
        ),
        migrations.AlterField(
            model_name='word',
            name='meaning',
            field=models.CharField(default='english', max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='sentence',
            field=models.CharField(default='example sentence', max_length=200),
        ),
    ]
