# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20171017_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('passage', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('tags', models.CharField(default='passage', max_length=1000)),
                ('date', models.DateTimeField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
